### ISSUE TITLE
First parameter must be a valid stream resource in

### ISSUE THREAD

**Issue by 334660335** [ratchetphp/Ratchet#1000]
Hi:
I have some problems, I use your demo code from your GitHub homepage.

My System:
x86_64 GNU/Linux

PHP Version: 
PHP 7.4.33 (cli) (built: Dec 19 2022 13:32:43) ( NTS )

PHP Code:
class MyChat implements MessageComponentInterface {
    protected $clients;

    public function __construct() {
        $this->clients = new \SplObjectStorage;
    }

    public function onOpen(ConnectionInterface $conn) {
        $this->clients->attach($conn);
    }

    public function onMessage(ConnectionInterface $from, $msg) {
        foreach ($this->clients as $client) {
            if ($from != $client) {
                $client->send($msg);
            }
        }
    }

    public function onClose(ConnectionInterface $conn) {
        $this->clients->detach($conn);
    }

    public function onError(ConnectionInterface $conn, \Exception $e) {
        $conn->close();
    }
}

// Run the server application through the WebSocket protocol on port 8080
$app = new Ratchet\App('localhost', 8088);
$app->route('/chat', new MyChat, array('*'));
$app->route('/echo', new Ratchet\Server\EchoServer, array('*'));
$app->run();

But when I start:  
`php test.php`

then I use telnet, it throws an exception:
```
telnet 127.0.0.1 8088
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
```

PHP Fatal error:  Uncaught InvalidArgumentException: First parameter must be a valid stream resource in /vendor/react/stream/src/WritableResourceStream.php:34
Stack trace:
#0 /vendor/react/socket/src/Connection.php(71): React\Stream\WritableResourceStream->__construct()
#1  /vendor/react/socket/src/TcpServer.php(255): React\Socket\Connection->__construct()
#2 /vendor/react/socket/src/TcpServer.php(235): React\Socket\TcpServer->handleConnection()
#3 /vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Socket\TcpServer->React\Socket\{closure}()
#4 /vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#5 /vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#6 /vendor/cboden/ratchet/src/Ratchet/App.php(145): Ratchet\Server\IoServer->run()
#7 /home/www/k in /vendor/react/stream/src/WritableResourceStream.php on line 34

-------------------

by the way
it's working at my local but can't use it on the server. 
could you give me some ideas or solutions?

thanks

**Comment by 334660335** [comment]
okay 
I think I've solute this problem
just edit php.ini
delete disable_functions: 
proc_open、stream_socket_server、**stream_socket_accept**
