### ISSUE TITLE
Can't start the server, port 8843 occupied

### ISSUE THREAD

**Issue by mikemix** [ratchetphp/Ratchet#410]
When trying to start the ws server I receive an error so service refuses to start:

> Chat server starting at 0.0.0.0:5559
> PHP Fatal error:  Uncaught exception 'React\Socket\ConnectionException' with message 'Could not bind to tcp://127.0.0.1:8843: Address already in use' in /var/www/app/vendor/react/socket/src/Server.php:29
> Stack trace:
> #0 /var/www/app/vendor/cboden/ratchet/src/Ratchet/App.php(93): React\Socket\Server->listen(8843)
> #1 /var/www/app/module/Chat/bin/server.php(21): Ratchet\App->__construct('localhost', '5559', '0.0.0.0')
> #2 {main}
>   thrown in /var/www/app/vendor/react/socket/src/Server.php on line 29

The port hardcoded by Ratchet `8843` is occupied on my FreeBSD server. Any help?

**Comment by mikemix** [comment]
Well I ended up writing my own WsServer class.
