### ISSUE TITLE
Expected either valid PHP Stream or valid PHP socket resource

### ISSUE THREAD

**Issue by dartkinselok** [ratchetphp/Ratchet#586]
Hello, guys. We have faced with huge problem that when we're starting WS server and users are going to connect. Earlier we have no libevent and event extension in PHP and have reached max 1024 connections in system. When we have installed it, limits were increased but appeared following error: `Expected either valid PHP Stream or valid PHP socket resource`

What should we do? Our software not working properly now and we can't handle users' connection... Thank you in advance!

Ping @cboden :)

**Comment by dartkinselok** [comment]
Stack trace:

```
Exception 'Exception' with message 'Expected either valid PHP stream or valid PHP socket resource'

in /home/www/mysite.com/vendor/react/event-loop/src/ExtEventLoop.php:283

Stack trace:
#0 /home/www/mysite.com/vendor/react/event-loop/src/ExtEventLoop.php(283): Event->set(Object(EventBase), Resource id #5348, 20, Object(Closure))
#1 /home/www/mysite.com/vendor/react/event-loop/src/ExtEventLoop.php(77): React\EventLoop\ExtEventLoop->unsubscribeStreamEvent(Resource id #5348, 2)
#2 /home/www/mysite.com/vendor/react/stream/src/DuplexResourceStream.php(105): React\EventLoop\ExtEventLoop->removeReadStream(Resource id #5348)
#3 /home/www/mysite.com/vendor/react/stream/src/DuplexResourceStream.php(139): React\Stream\DuplexResourceStream->pause()
#4 /home/www/mysite.com/vendor/react/stream/src/DuplexResourceStream.php(197): React\Stream\DuplexResourceStream->close()
#5 [internal function]: React\Stream\DuplexResourceStream->handleData(Resource id #5348, Object(React\EventLoop\ExtEventLoop))
#6 /home/www/mysite.com/vendor/react/event-loop/src/ExtEventLoop.php(318): call_user_func(Array, Resource id #5348, Object(React\EventLoop\ExtEventLoop))
#7 [internal function]: React\EventLoop\ExtEventLoop->React\EventLoop\{closure}(Resource id #5348, 6, NULL)
#8 /home/www/mysite.com/vendor/react/event-loop/src/ExtEventLoop.php(204): EventBase->loop(1)
#9 /home/www/mysite.com/commands/ServerController.php(44): React\EventLoop\ExtEventLoop->run()
#10 [internal function]: app\commands\ServerController->actionStart()
#11 /home/www/mysite.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /home/www/mysite.com/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#13 /home/www/mysite.com/vendor/yiisoft/yii2/console/Controller.php(128): yii\base\Controller->runAction('start', Array)
#14 /home/www/mysite.com/vendor/yiisoft/yii2/base/Module.php(523): yii\console\Controller->runAction('start', Array)
#15 /home/www/mysite.com/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('server/start', Array)
#16 /home/www/mysite.com/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('server/start', Array)
#17 /home/www/mysite.com/vendor/yiisoft/yii2/base/Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#18 /home/www/mysite.com/yii(21): yii\base\Application->run()
#19 {main}
```

**Comment by WyriHaximus** [comment]
@dartkinselok We're looking into this issue, can you show the output of `composer show | grep react`?

**Comment by dartkinselok** [comment]
```
react/cache                          v0.4.1             Async caching.
react/dns                            v0.4.11            Async DNS resolver for ReactPHP
react/event-loop                     v0.4.3             Event loop abstraction layer that libraries can use for evented I/O.
react/promise                        v2.5.1             A lightweight implementation of CommonJS Promises/A for PHP
react/promise-timer                  v1.2.0             Trivial timeout implementation for Promises
react/socket                         v0.8.6             Async, streaming plaintext TCP/IP and secure TLS socket server and cl...
react/stream                         v0.7.5             Event-driven readable and writable streams for non-blocking I/O in Re...
react/zmq                            v0.3.0             ZeroMQ bindings for React.
```

**Comment by dartkinselok** [comment]
@WyriHaximus  here it is:

```
react/cache                          v0.4.1             Async caching.
react/dns                            v0.4.11            Async DNS resolver for ReactPHP
react/event-loop                     v0.4.3             Event loop abstraction layer that libraries can use for evented I/O.
react/promise                        v2.5.1             A lightweight implementation of CommonJS Promises/A for PHP
react/promise-timer                  v1.2.0             Trivial timeout implementation for Promises
react/socket                         v0.8.6             Async, streaming plaintext TCP/IP and secure TLS socket server and cl...
react/stream                         v0.7.5             Event-driven readable and writable streams for non-blocking I/O in Re...
react/zmq                            v0.3.0             ZeroMQ bindings for React.
```

**Comment by WyriHaximus** [comment]
@dartkinselok thanks! For the time being could you try `composer require react/stream:v0.7.4`? That should fix the issue as a workaround until we fix this in our event loop.

**Comment by dartkinselok** [comment]
@WyriHaximus thank you, it was helped :) But I don't understand - **what this not working version do in master branch??**

**Comment by clue** [comment]
Thanks for your patience, fix is out via https://github.com/reactphp/event-loop/issues/136#issuecomment-353779427! :shipit: :+1:
